const rawContent = {
    "RobloxVersion": "Roblox Version: version-d343598577645e2",
    "AnchorId": "?",
    "Anchored": "?",
    "AnimationId": "?",
    "AttributeToIndex": "?",
    "AttributeToValue": "?",
    "AutoWeld": "?",
    "BeamColor": "?",
    "BeamLightEmission": "?",
    "BeamLightInfluence": "?",
    "Camera": "?",
    "CameraMaxZoomDistance": "?",
    "CameraMode": "?",
    "CanCollide": "?",
    "CanTouch": "?",
    "CharacterAppearanceId": "?",
    "Children": "?",
    "ClassDescriptor": "?",
    "ClickDetectorMaxActivationDistance": "?",
    "ClockTime": "?",
    "CreatorId": "?",
    "DataModelIterPointer": "?",
    "DataModelPrimitiveCount": "?",
    "DataModelRenderView": "?"
};
